### PR TITLE
Port to QWebEngine

### PR DESCRIPTION
**Pull request by qarkai**
Related to #7.
Ported partially. Only context menu works. No cookies, no cache.

### CODE REVIEW

**Comment by antonio-rojas** [comment]
Hi, Arch Linux qtwebkit maintainer here. Are you planning to follow up on this in the near future? Otherwise we'd have to drop smtube from the repos soon.

**Comment by qarkai** [comment]
@antonio-rojas
Short answer: no.
Long answer: I tried to build with Qt WebEngine and decided to share required changes with community. I'm not sure I able to port all features. I might add more patches later but can't say when.
Let's close this PR if it's confusing.

**Comment by barracuda156** [comment]
If anyone proceeds with this, please retain compat code for Qt4 systems, it is very much needed.

**Comment by smplayer-dev** [comment]
I'm not going to port smtube to QWebEngine. There wont' be any more releases of smtube.
I think it would better to write a widget for smplayer that uses the Youtube API to get the results.

**Comment by barracuda156** [comment]
> I'm not going to port smtube to QWebEngine. There wont' be any more releases of smtube. I think it would better to write a widget for smplayer that uses the Youtube API to get the results.

In principle, of course, a module in some working player is more convenient than a separate app which still has to call an external player.

**Comment by barracuda156** [comment]
@qarkai Just in case, if you will happen to be interested to complete this, please consider submitting a PR to Macports. (But we need to retain fallback code to support Qt4.)

**Comment by qarkai** [comment]
@barracuda156 I'm not interested anymore, sorry. Feel free to use any part of this PR that you find useful.

**Pull request closed without merging**
